integration:
  hmpps-auth:
    url: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
  tc-auth:
    url: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
  document-management:
    url: "https://document-api-preprod.hmpps.service.justice.gov.uk"
  manage-users:
    url: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
  template-configuration:
    url: "https://document-generation-api-dev.hmpps.service.justice.gov.uk"

service:
  allow-pulling-templates: true
  auto-pull-templates: true
  include-templates:
    - TAP_ROTL_23SCH
    - TAP_ROTL_APP
    - TAP_ROTL_BOARD
    - TAP_ROTL_COSPL
    - TAP_ROTL_COVIDV2
    - TAP_ROTL_DEC
    - TAP_ROTL_FNP
    - TAP_ROTL_LIC1
    - TAP_ROTL_LISP3_V3
    - TAP_ROTL_LISP5_V5
    - TAP_ROTL_MED1
    - TAP_ROTL_NOTIFY
    - TAP_ROTL_OM1
    - TAP_ROTL_POL1
    - TAP_TXCHKL_V1_1
